tenant_name: cicd_prod
app_name: hrms_app
epgs:
  - name: hrms_fe_epg
    bd: 192.168.21.0_24_bd
    prefGroup: no
    contracts:
      - contract: external_to_web_con
        type: consumer
      - contract: web_to_app_con
        type: consumer
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 301
  - name: hrms_be_epg
    bd: 192.168.22.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_db_con
        type: consumer
      - contract: web_to_app_con
        type: provider
      - contract: app_to_auth_con
        type: consumer
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 302
  - name: db_epg
    bd: 192.168.23.0_24_bd
    prefGroup: no
    contracts:
      - contract: cache_to_db_con
        type: provider
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 303
  - name: db_cache_epg
    bd: 192.168.23.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_db_con
        type: provider
      - contract: cache_to_db_con
        type: consumer
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 304
  - name: log_epg
    bd: 192.168.22.0_24_bd
    prefGroup: no
    contracts:
      - contract: any_to_log_con
        type: provider
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 305
  - name: auth_epg
    bd: 192.168.22.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_auth_con
        type: provider
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 306
  - name: jump_host
    bd: 192.168.22.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_auth_con
        type: provider
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: phys
        domain: iac_physdom
    ports:
      - interface: vpc_iac
        type: vpc
        mode: regular
        pod: 1
        leafs: 101-102
        encap: 307
