---
- name: Run Pre-change validation
  hosts: nd
  gather_facts: no

  vars:
    ig_name: SYD
    site_name: FAB1
    pcv_name: PCV_ANSIBLE5

  tasks:
    - name: Create a new Pre-Change analysis from file
      cisco.nd.nd_pcv:
        ig_name: "{{ ig_name }}"
        site_name: "{{ site_name }}"
        name: "{{ pcv_name }}"
        file: dryrun_data.json
        state: present

    - name: Get prechange validation status
      cisco.nd.nd_pcv:
        insights_group: "{{ ig_name }}"
        site_name: "{{ site_name }}"
        name: "{{ pcv_name }}"
        state: wait_and_query


    - name: query a pre_change analysis
      cisco.nd.nd_pcv_delta_analysis:
        ig_name: "{{ ig_name }}"
        site_name: "{{ site_name }}"
        name: "{{ pcv_name }}"
        epoch_choice: 'epoch2'
      register: pcv_result

    - name: PCV Result
      ansible.builtin.debug:
        msg:
          - Detected anomalies by severity
          - critical = {{pcv_result.current.anomaly_count.critical.epoch2_only}}
          - major = {{pcv_result.current.anomaly_count.major.epoch2_only}}
          - minor = {{pcv_result.current.anomaly_count.minor.epoch2_only}}
          - warning = {{pcv_result.current.anomaly_count.warning.epoch2_only}}
